export const classes = [
    { id: 1, name: "Berserker" },
    { id: 2, name: "Destroyer" },
    { id: 3, name: "Gunlancer" },
    { id: 4, name: "Paladin" },
    { id: 5, name: "Bard" },
    { id: 6, name: "Sorceress" },
    { id: 7, name: "Wardancer" },
    { id: 8, name: "Scrapper" },
    { id: 9, name: "Soulfist" },
    { id: 10, name: "Glaivier" },
    { id: 11, name: "Striker" },
    { id: 12, name: "Deathblade" },
    { id: 13, name: "Shadowhunter", },
    { id: 14, name: "Sharpshooter" },
    { id: 15, name: "Deadeye" },
    { id: 16, name: "Artillerist" },
    { id: 17, name: "Gunslinger" },
]

export const positiveEngravings = [
    { id: 1, name: "Barrage Enhancement", class: "Artillerist", icon: 'img/engravings/gl_skill_01_26.webp' },
    { id: 2, name: "Berserker's Technique", class: "Berserker", icon: 'img/engravings/buff_138.webp' },
    { id: 3, name: "Blessed Aura", class: "Paladin", icon: 'img/engravings/ability_215.webp' },
    { id: 4, name: "Combat Readiness", class: "Gunlancer", icon: 'img/engravings/buff_19.webp' },
    { id: 5, name: "Control", class: "Glaivier", icon: 'img/engravings/ability_208.webp' },
    { id: 6, name: "Death Strike", class: "Sharpshooter", icon: 'img/engravings/buff_245.webp' },
    { id: 7, name: "Deathblow", class: "Striker", icon: 'img/engravings/ability_230.webp' },
    { id: 8, name: "Demonic Impulse", class: "Shadowhunter", icon: 'img/engravings/ability_212.webp' },
    { id: 9, name: "Desperate Salvation", class: "Bard", icon: 'img/engravings/buff_135.webp' },
    { id: 10, name: "Energy Overflow", class: "Soulfist", icon: 'img/engravings/buff_235.webp' },
    { id: 11, name: "Enhanced Weapon", class: "Deadeye", icon: 'img/engravings/buff_33.webp' },
    { id: 12, name: "Esoteric Flurry", class: "Striker", icon: 'img/engravings/ability_229.webp' },
    { id: 13, name: "Esoteric Skill Enhancement", class: "Wardancer", icon: 'img/engravings/buff_238.webp' },
    { id: 14, name: "Firepower Enhancement", class: "Artillerist", icon: 'img/engravings/buff_171.webp' },
    { id: 15, name: "First Intention", class: "Wardancer", icon: 'img/engravings/ability_25.webp' },
    { id: 16, name: "Gravity Training", class: "Destroyer", icon: 'img/engravings/buff_42.webp' },
    { id: 17, name: "Igniter", class: "Sorceress", icon: 'img/engravings/ability_240.webp' },
    { id: 18, name: "Judgment", class: "Paladin", icon: 'img/engravings/ability_214.webp' },
    { id: 19, name: "Lone Knight", class: "Gunlancer", icon: 'img/engravings/buff_13.webp' },
    { id: 20, name: "Loyal Companion", class: "Sharpshooter", icon: 'img/engravings/buff_77.webp' },
    { id: 21, name: "Mayhem", class: "Berserker", icon: 'img/engravings/buff_173.webp' },
    { id: 22, name: "Peacemaker", class: "Gunslinger", icon: 'img/engravings/ability_225.webp' },
    { id: 23, name: "Perfect Suppression", class: "Shadowhunter", icon: 'img/engravings/ability_211.webp' },
    { id: 24, name: "Pinnacle", class: "Glaivier", icon: 'img/engravings/ability_207.webp' },
    { id: 25, name: "Pistoleer", class: "Deadeye", icon: 'img/engravings/buff_124.webp' },
    { id: 26, name: "Rage Hammer", class: "Destroyer", icon: 'img/engravings/achieve_08_49.webp' },
    { id: 27, name: "Reflux", class: "Sorceress", icon: 'img/engravings/ability_241.webp' },
    { id: 28, name: "Remaining Energy", class: "Deathblade", icon: 'img/engravings/ability_209.webp' },
    { id: 29, name: "Robust Spirit", class: "Soulfist", icon: 'img/engravings/ability_45.webp' },
    { id: 30, name: "Shock Training", class: "Scrapper", icon: 'img/engravings/buff_177.webp' },
    { id: 31, name: "Surge", class: "Deathblade", icon: 'img/engravings/ability_210.webp' },
    { id: 32, name: "Time to Hunt", class: "Gunslinger", icon: 'img/engravings/ability_228.webp' },
    { id: 33, name: "True Courage", class: "Bard", icon: 'img/engravings/buff_220.webp' },
    { id: 34, name: "Ultimate Skill: Taijutsu", class: "Scrapper", icon: 'img/engravings/achieve_07_22.webp' },
    { id: 35, name: "Adrenaline", class: "", icon: 'img/engravings/ability_235.webp' },
    { id: 36, name: "All-Out Attack", class: "", icon: 'img/engravings/ability_236.webp' },
    { id: 37, name: "Ambush Master", class: "", icon: 'img/engravings/buff_148.webp' },
    { id: 38, name: "Awakening", class: "", icon: 'img/engravings/buff_113.webp' },
    { id: 39, name: "Barricade", class: "", icon: 'img/engravings/buff_170.webp' },
    { id: 40, name: "Broken Bone", class: "", icon: 'img/engravings/buff_94.webp' },
    { id: 41, name: "Contender", class: "", icon: 'img/engravings/buff_136.webp' },
    { id: 42, name: "Crisis Evasion", class: "", icon: 'img/engravings/buff_162.webp' },
    { id: 43, name: "Crushing Fist", class: "", icon: 'img/engravings/buff_83.webp' },
    { id: 44, name: "Cursed Doll", class: "", icon: 'img/engravings/buff_237.webp' },
    { id: 45, name: "Disrespect", class: "", icon: 'img/engravings/achieve_04_30.webp' },
    { id: 46, name: "Divine Protection", class: "", icon: 'img/engravings/buff_229.webp' },
    { id: 47, name: "Drops of Ether", class: "", icon: 'img/engravings/buff_18.webp' },
    { id: 48, name: "Emergency Rescue", class: "", icon: 'img/engravings/ability_238.webp' },
    { id: 49, name: "Enhanced Shield", class: "", icon: 'img/engravings/buff_239.webp' },
    { id: 50, name: "Ether Predator", class: "", icon: 'img/engravings/buff_74.webp' },
    { id: 51, name: "Expert", class: "", icon: 'img/engravings/ability_237.webp' },
    { id: 52, name: "Explosive Expert", class: "", icon: 'img/engravings/buff_121.webp' },
    { id: 53, name: "Fortitude", class: "", icon: 'img/engravings/buff_66.webp' },
    { id: 54, name: "Grudge", class: "", icon: 'img/engravings/buff_71.webp' },
    { id: 55, name: "Heavy Armor", class: "", icon: 'img/engravings/buff_46.webp' },
    { id: 56, name: "Hit Master", class: "", icon: 'img/engravings/ability_233.webp' },
    { id: 57, name: "Keen Blunt Weapon", class: "", icon: 'img/engravings/achieve_03_40.webp' },
    { id: 58, name: "Lightning Fury", class: "", icon: 'img/engravings/buff_191.webp' },
    { id: 59, name: "Magick Stream", class: "", icon: 'img/engravings/buff_63.webp' },
    { id: 60, name: "Mass Increase", class: "", icon: 'img/engravings/ability_231.webp' },
    { id: 61, name: "Master Brawler", class: "", icon: 'img/engravings/ability_224.webp' },
    { id: 62, name: "Master of Escape", class: "", icon: 'img/engravings/buff_10.webp' },
    { id: 63, name: "Master's Tenacity", class: "", icon: 'img/engravings/buff_147.webp' },
    { id: 64, name: "Max MP Increase", class: "", icon: 'img/engravings/buff_122.webp' },
    { id: 65, name: "MP Efficiency Increase", class: "", icon: 'img/engravings/buff_166.webp' },
    { id: 66, name: "Necromancy", class: "", icon: 'img/engravings/buff_29.webp' },
    { id: 67, name: "Precise Dagger", class: "", icon: 'img/engravings/ability_239.webp' },
    { id: 68, name: "Preemptive Strike", class: "", icon: 'img/engravings/achieve_08_62.webp' },
    { id: 69, name: "Propulsion", class: "", icon: 'img/engravings/ability_232.webp' },
    { id: 70, name: "Raid Captain", class: "", icon: 'img/engravings/buff_210.webp' },
    { id: 71, name: "Shield Piercing", class: "", icon: 'img/engravings/buff_89.webp' },
    { id: 72, name: "Sight Focus", class: "", icon: 'img/engravings/ability_234.webp' },
    { id: 73, name: "Spirit Absorption", class: "", icon: 'img/engravings/buff_65.webp' },
    { id: 74, name: "Stabilized Status", class: "", icon: 'img/engravings/buff_105.webp' },
    { id: 75, name: "Strong Will", class: "", icon: 'img/engravings/buff_44.webp' },
    { id: 76, name: "Super Charge", class: "", icon: 'img/engravings/achieve_06_14.webp' },
    { id: 77, name: "Vital Point Hit", class: "", icon: 'img/engravings/buff_168.webp' },
]

export const negativeEngravings = [
    { id: 1, name: "Atk. Power Reduction", icon: 'img/engravings/ability_218.webp' },
    { id: 2, name: "Atk. Speed Reduction", icon: 'img/engravings/ability_220.webp' },
    { id: 3, name: "Defense Reduction", icon: 'img/engravings/ability_219.webp' },
    { id: 4, name: "Move Speed Reduction", icon: 'img/engravings/ability_221.webp' },
]
